from pydantic import BaseModel
from typing import List, Optional, Dict, Any

# -------- Chat --------
class ChatMessage(BaseModel):
    """
    Reponsents a single message in a chat conversation.

    Attributes:
        role (str): The role of the message sender (e.g., 'user', 'assistant').
        content (str): The actual text content of the message.
    """
    role: str
    content: str

class ChatRequest(BaseModel):
    """
    Request model for the chat endpoint.

    Attributes:
        messages (List[ChatMessage]): The history of messages in the conversation.
    """
    messages: List[ChatMessage]

class ChatResponse(BaseModel):
    """
    Response model for the chat endpoint.

    Attributes:
        reply (str): The response text generated by the AI agent.
    """
    reply: str

# -------- File-based --------
class FileResponse(BaseModel):
    """
    Generic response model for file processing endpoints.

    Attributes:
        status (str): The outcome of the operation ('success' or 'failure').
        data (Dict[str, Any] | None): The structured data result on success.
        issues (List[str] | None): A list of error messages or issues found on failure.
        next_steps (List[str] | None): Suggested actions for the user to resolve issues.
    """
    status: str
    data: Dict[str, Any] | None = None
    issues: List[str] | None = None
    next_steps: List[str] | None = None


class LineItem(BaseModel):
    """
    Represents a single line item in an invoice or PO.
    """
    sno: int
    description: str
    hsn_code: str
    quantity: int
    unit_rate: float
    amount: float

class Party(BaseModel):
    """
    Represents an entity involved in the transaction (Vendor, Buyer, etc.).
    """
    name: str
    address: str
    gstin: Optional[str] = None
    state: str

class Tax(BaseModel):
    """
    Represents the tax breakdown for the transaction.
    """
    cgst: Optional[float] = 0
    sgst: Optional[float] = 0
    igst: Optional[float] = 0

class InvoiceSchema(BaseModel):
    """
    Complete schema for a structured Invoice.

    Attributes:
        po_number (str): The Purchase Order number reference.
        invoice_date (str): Date of invoice issuance.
        delivery_date (str): Expected or actual delivery date.
        payment_terms (str): Agreed payment terms.
        amount_in_words (str): Total amount written in words.
        vendor (Party): The supplier/vendor details.
        ship_to (Party): The shipping destination details.
        sold_to (Party): The billing entity details.
        line_items (List[LineItem]): List of items purchased.
        subtotal (float): Total before tax.
        taxes (Tax): Tax components.
        total_amount (float): Final payable amount.
        notes (List[str]): Additional notes or conditions.
    """
    po_number: str
    invoice_date: str
    delivery_date: str
    payment_terms: str
    amount_in_words: str

    vendor: Party
    ship_to: Party
    sold_to: Party

    line_items: List[LineItem]
    subtotal: float
    taxes: Tax
    total_amount: float
    notes: List[str]
